version: '3.7'
services:
  proxy:
    build: ./nginx/.
    image: pabliny5/nginx:1.0
    ports:
      - 80:80
    depends_on:
      - motorcycle-app
      - motorcycle-api
    networks:
      - front_net
      - back_net
  motorcycle-app:
    build: ./frontend/motorcycle-app/.
    image: pabliny5/motorcycle-app:1.0
    depends_on:
      - motorcycle-api
    ports:
      - 3000:3000
    networks:
      - front_net
  motorcycle-api:
    build: ./backend/motorcycle-api/.
    image: pabliny5/motorcycle-api:1.0
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/motorcycle_db
      MYSQL_USERNAME: workshop_user
      MYSQL_PASSWORD: Workshop_1234
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - front_net
      - back_net
  db:
    build: ./database/.
    image: pabliny5/motorcycle-db:1.0
    restart: always
    volumes:
      - "motorcyle-db-data:/app"
    networks:
      - back_net

volumes:
  motorcyle-db-data:

networks:
  back_net:
  front_net: